# You can configure many Jekyll options, overriding defaults in this file.
# Possible options are here: https://github.com/mojombo/jekyll/wiki/Configuration

## IMPORTANT ##
# If, like me, you prefer tabs over spaces for indentation, polease be aware that using tabs in YAML
# files used by Jekyll breaks stuff. Don't do that. Single space only in YAML front matter.

auto: true

# Instantiate gems
# gems: [jekyll-pagination]

 # This will require each of these gems automatically.

# Seth the default URL structure for posts. See for details:
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: post/:title

version: 0.1

# Pagination
paginate: 5
paginate_path: "posts/page:num"

# PERSONALISE ME!
sitename: matt-thomas.me
# Replace these details with your own (You can remove everything beginning name: if you don't use them)
author :
 name: Matt Thomas
 email: me@matt-thomas.me
 github: betweenbrain
 twitter: betweenbrain
 disqus: betweenbrain

# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://betweenbrain.github.com
